package com.example.coup_bench.model.Enums;

public enum GameState {
    WAITING_FOR_PLAYERS,
    IN_PROGRESS,
    ACTION_DECLARED,
    CHALLENGE_DECLARED,
    BLOCK_DECLARED,
    BLOCK_PENDING,
    CHALLENGE_PENDING,
    RESOLVING_CHALLENGE,
    APPLYING_ACTION,
    REMOVING_CARD,
    FINISHED
}

