package com.example.coup_bench.model.Enums;

public enum GameState {
    WAITING_FOR_PLAYERS,
    CHALLENGE_DECLARED,
    BLOCK_DECLARED,
    FINISHED,
    APPLY_ACTION,
    NEXT_TURN,
    WAITING_FOR_ACTION,
    WAITING_FOR_HUMAN_ACTION,
    WAITING_FOR_CHALLENGE,
    ENDGAME,
    DECLARE_ACTION,
    INVALID
}

