package com.example.coup_bench.model.Enums;

public enum GameState {
    WAITING_FOR_PLAYERS,
    IN_PROGRESS,
    ACTION_DECLARED,
    CHALLENGE_DECLARED,
    BLOCK_DECLARED,
    APPLYING_ACTION,
    FINISHED,
    APPLY_CHALLENGE, APPLY_ACTION, APPLY_BLOCK, DECIDING_ACTION, NEXT_TURN, WAITING_FOR_ACTION, WAITING_FOR_HUMAN_ACTION, WAITING_FOR_CHALLENGE, ENDGAME, INVALID
}

